FROM python:3.11-slim

WORKDIR /app

COPY requirements /app/requirements

RUN python -m pip install --upgrade pip && \
    pip install --no-cache-dir --default-timeout=300 mlflow

COPY . .

EXPOSE 5000

CMD [
    "mlflow",
    "ui",
    "--backend-store-uri",
    "sqlite:///mlflow.db",
    "--host",
    "0.0.0.0",
    "--port",
    "5000"
]